#!/bin/bash
# Domain information script

#Quit if no argument supplied
if [[ $# -eq 0 ]] ; then
    echo 'No argument supplied. Exiting...'
    exit 1
fi

#Save supplied argument in variable DOMAIN
DOMAIN=$1

#Domain General info (whois)
echo "General and public information from whois:"
whois $1 | grep -w 'Registrant\|Admin\|Tech'
echo "#################################"
echo " "

#SOA Record
echo "SOA Records:"
host -t soa $1
echo "#################################"
echo " "

#A Records
echo "A Records:"
host -t a $1
echo "#################################"
echo " "

#CNAME Records
echo "CNAME Records:"
host -t cname $1
echo "#################################"
echo " "

#MX Records
echo "MX Records:"
host -t mx $1
echo "#################################"
echo " "

#TXT Records
echo "TXT Records:"
host -t txt $1
echo "#################################"
echo " "

#Name Servers
echo "Name servers:"
host -t ns $1
echo "#################################"
echo " "
